org:
  issue_types:
  - name: Issue
    description: Some issue description here
  - name: Other Issue

labels:
  - name: Some label
    descripion: Label description
    color: ff0000
  - name: duplicate

repository:
  description: null
  homepage: https://example.com
  private: false
  security_and_analysis:
    secret_scanning:
      status: enabled
    secret_scanning_push_protection:
      status: disabled
    secret_scanning_ai_detection:
      status: disabled
    secret_scanning_non_provider_patterns:
      status: disabled
  has_issues: true
  has_projects: true
  has_wiki: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_auto_merge: false
  delete_branch_on_merge: true
  allow_update_branch: true
  squash_merge_commit_title: PR_TITLE
