org:
  issue_types:
  - name: Issue
    description: Some issue description here
  - name: Other Issue

# ello
repository:
  description: null
  homepage: https://example.com
  private: false
  security_and_analysis:
    secret_scanning:
      status: enabled 
