org:
  issue_types:
  - name: Issue
    description: Some issue description here
  - name: Other Issue

repository:
  description: null
  homepage: https://example.com
  private: false
  security_and_analysis:
    secret_scanning:
      status: enabled
    secret_scanning_push_protection:
      status: disabled
    secret_scanning_ai_detection:
      status: disabled
    secret_scanning_non_provider_patterns:
      status: disabled
  has_issues: false
  has_projects: true
  has_wiki: false
