org:
  issue_types:
  - name: Issue
    description: Some issue description here
  - name: Other Issue

# ello
repository:
  description: null
  homepage: https://example.com
  private: false
  security_and_analysis:
    advanced_security:
      status: enabled
    code_security:
      status: enabled
    secret_scanning:
      status: enabled
    secret_scanning_push_protection:
      status: disabled
    secret_scanning_ai_detection:
      status: disabled
    secret_scanning_non_provider_patterns:
      status: disabled
