org:
  issue_types:
  - name: Issue
    description: Some issue description here
  - name: Other Issue

repository:
  # description: description goes here
  name: .github 
  has_issues: true
  has_wiki: true
  allow_merge_commit: false
  allow_squash_commit: false
  allow_rebase_merge: false
