org:
  issue_types:
  - name: 'Issue'
    description: Some issue description here
  - name: 'Other Issue'

repository:
  has_wiki: true
  allow_merge_commit: false
  allow_squash_commit: true
  allow_rebase_merge: false
